./main ../test_cases/more/input0.txt ../test_cases/more/outputs/out0.txt
./main ../test_cases/more/input1.txt ../test_cases/more/outputs/out1.txt
./main ../test_cases/more/input2.txt ../test_cases/more/outputs/out2.txt
./main ../test_cases/more/input3.txt ../test_cases/more/outputs/out3.txt
./main ../test_cases/more/input4.txt ../test_cases/more/outputs/out4.txt
./main ../test_cases/more/input5.txt ../test_cases/more/outputs/out5.txt
./main ../test_cases/more/input6.txt ../test_cases/more/outputs/out6.txt
./main ../test_cases/more/input7.txt ../test_cases/more/outputs/out7.txt
./main ../test_cases/more/input8.txt ../test_cases/more/outputs/out8.txt
./main ../test_cases/more/input9.txt ../test_cases/more/outputs/out9.txt
./main ../test_cases/more/input10.txt ../test_cases/more/outputs/out10.txt
